name: deepcdr_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=5_kmp_llvm
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython=7.33.0=py37h89c1867_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.5=h4922eb0_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2022.2.1=h6508926_16999
  - mkl-service=2.4.0=py37h94185c7_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.3=py37h540881e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.2=h8c095d6_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sqlite=3.51.0=heff268d_0
  - tbb=2021.13.0=hb60516a_3
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.2=py37h540881e_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h75354e8_4
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.1.0
      - astor==0.8.1
      - dill==0.3.7
      - gast==0.6.0
      - grpcio==1.62.3
      - h5py==2.10.0
      - hickle==5.0.3
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - keras==2.1.4
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - markdown==3.4.4
      - markupsafe==2.1.5
      - mock==5.2.0
      - numpy==1.21.6
      - pandas==1.3.5
      - protobuf==3.20.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - scikit-learn==1.0.2
      - scipy==1.5.4
      - six==1.17.0
      - tensorboard==1.13.1
      - tensorflow==1.13.1
      - tensorflow-estimator==1.13.0
      - termcolor==2.3.0
      - theano==1.0.5
      - threadpoolctl==3.1.0
      - typing-extensions==4.7.1
      - werkzeug==2.2.3
      - zipp==3.15.0
prefix: /home/sunag/miniforge3/envs/deepcdr_env
